-- Add guest question templates for easy messaging
INSERT INTO public.chat_templates (category, title, message, sort_order, is_active) VALUES
('room_requests', 'Extra Pillows', 'Can I get extra pillows for my room?', 1, true),
('room_requests', 'Extra Towels', 'I need more towels in my room', 2, true),
('room_requests', 'Room Temperature', 'My room is too hot/cold, can you help?', 3, true),
('room_requests', 'Extra Blankets', 'Can I get extra blankets?', 4, true),
('room_requests', 'Water Bottles', 'Can I get some water bottles delivered?', 5, true),
('dining', 'Restaurant Reservation', 'Can you help me make a restaurant reservation?', 1, true),
('dining', 'Room Service Menu', 'Can I see the room service menu?', 2, true),
('dining', 'Restaurant Hours', 'What are the restaurant hours?', 3, true),
('dining', 'Dietary Requirements', 'I have dietary restrictions, can you help?', 4, true),
('hotel_info', 'Pool Hours', 'What are the pool hours?', 1, true),
('hotel_info', 'Checkout Time', 'What time is checkout?', 2, true),
('hotel_info', 'Hotel Amenities', 'What amenities does the hotel have?', 3, true),
('hotel_info', 'Fitness Center', 'Where is the fitness center and what are the hours?', 4, true),
('hotel_info', 'Late Checkout', 'Can I get a late checkout?', 5, true),
('technical', 'WiFi Help', 'How do I connect to WiFi?', 1, true),
('technical', 'TV Issues', 'My TV is not working properly', 2, true),
('technical', 'Room Key', 'My room key is not working', 3, true),
('local_info', 'Nearby Restaurants', 'What restaurants are nearby?', 1, true),
('local_info', 'Local Attractions', 'What attractions should I visit?', 2, true),
('local_info', 'Transportation', 'How do I get to the airport?', 3, true),
('local_info', 'Shopping', 'Where can I go shopping nearby?', 4, true);